### ISSUE TITLE
Update general structure of MHCbinding subworkflow 

### ISSUE THREAD

**Issue by alina-bauer** [nf-core/epitopeprediction#205]
It should be a subworkflow that replaces the function [make_predictions_from_peptides](https://github.com/nf-core/epitopeprediction/blob/b0f0d7a5b3cd352e548901e4cc19937c73add465/bin/epaa.py#L1111C5-L1111C35) in epaa.py.
That subworkflow takes as input a tsv file containing a column sequence (and additional metadata). Depending on the tools specified by the user one or more predictors can be used.
First there will be a general structure that can be executed with the `-stub` parameter without any functionality.

![](https://user-images.githubusercontent.com/43858870/255527974-69928053-41ae-426a-9503-b6c818d6cbaa.png)

```[tasklist]
### Tasks
- [ ] https://github.com/nf-core/epitopeprediction/issues/214
- [ ] https://github.com/nf-core/epitopeprediction/issues/215
- [ ] https://github.com/nf-core/epitopeprediction/issues/216
- [ ] https://github.com/nf-core/epitopeprediction/issues/217
```
